# Generated by Django 4.2.5 on 2023-10-04 16:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(default='', max_length=18, unique=True)),
                ('Title', models.CharField(default='', max_length=80, unique=True)),
                ('Authors', models.CharField(default='', max_length=150)),
                ('Publisher', models.CharField(default='', max_length=150)),
                ('Publication_Date', models.CharField(default='', max_length=150)),
                ('Genre', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=500)),
                ('Price', models.FloatField()),
                ('Quantity_Stocks', models.CharField(default='', max_length=150)),
                ('Language', models.CharField(default='', max_length=150)),
                ('Synopsis', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='', max_length=500)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Ratings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_rated', to='api.feedback'),
        ),
        migrations.AddField(
            model_name='book',
            name='Reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.feedback'),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ManyToManyField(to='api.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='rated_books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_rated_books', to='api.feedback'),
        ),
        migrations.AddField(
            model_name='account',
            name='reviewed_books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reviewed_books', to='api.feedback'),
        ),
        migrations.AddField(
            model_name='account',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
        migrations.AddField(
            model_name='account',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='account',
            name='transactions_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_history', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
