# Generated by Django 4.2.5 on 2023-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_ratings_alter_book_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='Synopsis',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
