# Generated by Django 4.2.5 on 2023-10-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
